config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'posts#index', as: 'home'
  get 'resimler' => 'pages#resimler'
  get 'about'=> 'pages#about', as: 'about'
  resources :posts do
  	resources :comments	


  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comments
	validates :title, presence: true,
					  length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!
	def about
		@title = 'About Us';
		@content = 'Bu sayfa Hakkında Sayfasıdır'
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	
	

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new

		@post= Post.new
	end

	def create 
		#render plain: params[:post].inspect
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		
		@post = Post.find(params[:id])

	end

	def update 

		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

		def destroy 
			@post = Post.find(params[:id])
			@post.destroy

			redirect_to posts_path

		end
	private def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  	<nav class="p-3 mb-2 bg-info text-white" class="navbar navbar-default">

      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="about">Blog Sitem</a>
        </div>
        <div  id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav ">
            <li><%= link_to "Ana Sayfa", home_path %></li>
          </ul>
        
          <ul class="nav navbar-nav navbar-right">
            <li ><%= link_to "Çıkış", destroy_user_session_path, :method=> :delete %></li>
          </ul>
         
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Yeni Yazı", new_post_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
    	




    <%= yield %>
        </div >

  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="la.jpg" alt="Los Angeles" style="width:100%;">
      </div>

      <div class="item">
        <img src="chicago.jpg" alt="Chicago" style="width:100%;">
      </div>
    
      <div class="item">
        <img src="ny.jpg" alt="New york" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Yazı Ekle</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class='alert alert-danger'></div>	
		<%end%>
	<%end%>
	<p>
		<%=f.label :title %> <br>
		<%=f.text_field :title %> <br>
	</p>
	<p> 
		<%=f.label :body %> <br>
		<%=f.text_area :body %> <br>
	</p>
	
	<p> 
		<%=f.submit({:class => 'btn btn-primary'}) %> 
	</p>
<%end%> 

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post|%>
	
	<div class="well">
		<h3><%=post.title%></h3>
		<p><%= post.body %></p>
		<%=link_to "Oku", post_path(post), :class => 'btn btn-success' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>

<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class='alert alert-danger'></div>	
		<%end%>
	<%end%>
	<p>
		<%=f.label :title %> <br>
		<%=f.text_field :title %> <br>
	</p>
	<p> 
		<%=f.label :body %> <br>
		<%=f.text_area :body %> <br>
	</p>
	
	<p> 
		<%=f.submit({:class => 'btn btn-primary'}) %> 
	</p>
		
<%end%> 

app/views/posts/resimler.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  	<nav class="p-3 mb-2 bg-info text-white" class="navbar navbar-default">

      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="resimler">Blog Sitem</a>
        </div>
        <div  id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav ">
            <li><%= link_to "Ana Sayfa", home_path %></li>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Yeni Yazı", new_post_path %></li>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
    	




    <%= yield %>
        </div >

  </body>
</html>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), 
			
			method: :delete, 
			data: {confirm: 'Eminmisiniz ?'},

						:class => 'btn btn-danger' %>